### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by habbes** [AfricasTalkingLtd/africastalking-python#1]
Does this library support Python 3?
Tried to import the library in python 3 script using pip and it through a syntax error due to the print statements without parentheses.

**Comment by ianjuma** [comment]
no, not at the moment - just 2 for now. Haven't tried but adding parens might work.

**Comment by habbes** [comment]
I also think the urllib2 package has different API's in Python 2 and 3, so that might also be a compatibility issue.

**Comment by ianjuma** [comment]
that was a long shot :laughing:  - I really want to move this to requests and have just one API. 
For now you could check the docs and use requests. All the endpoints are there and well documented.

**Comment by habbes** [comment]
Yeah, that's what did, I used requests.
