### ISSUE TITLE
[BUG]: `getUserData` method is broken.

### ISSUE THREAD

**Issue by mattgathu** [AfricasTalkingLtd/africastalking-python#11]
The [`getUserData` method](https://github.com/AfricasTalkingLtd/africastalking-python/blob/master/africastalking/AfricasTalkingGateway.py#L274) always returns `AfricasTalkingGatewayException`.

On further probing, it turns out the method makes a `POST` requests instead of a `GET` request to the api endpoint. This is because of how the [sendRequest](https://github.com/AfricasTalkingLtd/africastalking-python/blob/master/africastalking/AfricasTalkingGateway.py#L283) method is implemented.

How to reproduce:

```python
url = 'https://api.africastalking.com/version1/user?username=your-username'
headers = { 'Accept' : 'application/json',  'apikey' : XXXX}
r = requests.post(url, headers)
print(r.status_code) # status code: 405
print(r.test) # text: HTTP method not allowed, supported methods: GET
```
I apologize I have used `requests` to reproduce the error instead of the `AfricasTalkingGateway` class. This because the error gets masked by the `AfricasTalkingGatewayException` I'm using requests to simulate [this line](https://github.com/AfricasTalkingLtd/africastalking-python/blob/master/africastalking/AfricasTalkingGateway.py#L289) in `sendRequest`.

Changing the http method from `POST` to `GET` fixes this:
```python
url = 'https://api.africastalking.com/version1/user?username=your-username'
headers = { 'Accept' : 'application/json',  'apikey' : XXXX}
r = requests.get(url, headers)
print(r.status_code) # status code: 200
print(r.test) # text:{'UserData': {'balance': 'KES XXX'}}
```

**Comment by ianjuma** [comment]
This must have changed internally; I have changed it back. Making a push in a bit.
