### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by johngathure** [AfricasTalkingLtd/africastalking-python#12]
![screenshot from 2018-03-18 14-36-51](https://user-images.githubusercontent.com/16336444/37565633-e1dd07ee-2abd-11e8-8220-cee8526faa92.png)
![screenshot from 2018-03-18 14-57-37](https://user-images.githubusercontent.com/16336444/37565636-ee318a9c-2abd-11e8-9e98-065da60082bc.png)

**Comment by whatnick** [comment]
I believe this is due to Python 3.6, because it uses an absolute import, and not a relative imports. A version detection and appropriate import calls need to be performed to deal with this.
