### ISSUE TITLE
Misleading exception

### ISSUE THREAD

**Issue by TheBeachMaster** [AfricasTalkingLtd/africastalking-python#23]
Spotted in this conversation -> https://africastalking.slack.com/archives/C034H1KLL/p1554381518034600 

https://github.com/AfricasTalkingLtd/africastalking-python/blob/93cf080f3a1a84a209c2443b11c313d092e4a80f/africastalking/Payment.py#L68-L69

**Comment by kevokevoh** [comment]
Thank you @TheBeachMaster
