### ISSUE TITLE
BAD STATUS LINE 

### ISSUE THREAD

**Issue by eliaskioni** [AfricasTalkingLtd/africastalking-python#3]
I had raised this issue with your support team but I feel the response was not correct. 

The exception is really been caused by bad response from your servers which the AfricasTalking Module should handle If am not wrong and quoting this. 

> # Any gateway errors will be captured by our custom Exception class below, 
# so wrap the call in a try-catch block

What worries is it does not happen all of the time. Actually we worked around this by waiting for some seconds and sending the payload again if this exemption is raised. 

Here is the issue I had filed. 

Bug Report 
 
According to your documention this will catch all errors. 

# Any gateway errors will be captured by our custom Exception class below, 
# so wrap the call in a try-catch block
```
try:
    # Thats it, hit send and we'll take care of the rest.
    
    results = gateway.sendMessage(to, message)
    
    for recipient in results:
        # status is either "Success" or "error message"
        print 'number=%s;status=%s;messageId=%s;cost=%s' % (recipient['number'],
                                                            recipient['status'],
                                                            recipient['messageId'],
                                                            recipient['cost'])
except AfricasTalkingGatewayException, e:
    print 'Encountered an error while sending: %s' % str(e)

```
However if am not lost a custom exception will only capture exceptions of its type hence this BAD REQUEST EXCEPTION WILL BE IGNORED by this AfricasTalkingGatewayException. 

proof:

try this 

class AfricasTalkingGatewayException(Exception):
    pass

def bug():
    try:
        12/0
    except AfricasTalking as e:
        print("Code will not reach here. Exception will not be caught")

**_I raised this because it got us in trouble though not serious._**

**Comment by ianjuma** [comment]
Are you not supposed to catch the broader exception with another Exception class? 
So, in this case; **BadRequestException**

```python
class AfricasTalkingGatewayException(Exception):
    pass

def bug():
    try:
        12/0
    except AfricasTalkingGatewayException as e:
        print("Code will not reach here. Exception will not be caught")
    except Exception as p:
        print p

bug()
```

I did catch all here - and got an exception divide by zero.
Also check implementation here - https://github.com/twilio/twilio-python/search?utf8=%E2%9C%93&q=exception

What change proposal do you have? I really don't understand this problem.

**Comment by eliaskioni** [comment]
Problem solved

**Comment by eliaskioni** [comment]
Hi Grace.

Sorry for not replying in time and for causing the trouble - this bug
issue.

We had a busy start of the week hence the lateness to replying to your
email.

I think am not able to explain myself well and also we might be wrong in
how we are handling our sms system. But we are still getting the bad
exception though we can deal with it.

So as a solution I tried to create a project that tries to tell what we are
saying.

You or someone else who can.  Clone this repo -  BADSTATUSLINE
<https://github.com/eliaskioni/BadStatusLine>, run the project and
hopefully you will get an idea of what we are saying.  The README outlines
how to run the project and etc.

Am also attaching an excel file with numbers because this issue only
happens while sending SMSes to many numbers. Please take care of our excel
file. The numbers are real.

Write to me in case of anything. We can also do the call.

Kind Regards.

- Elias Kioni
