### ISSUE TITLE
USSD service using Python

### ISSUE THREAD

**Issue by roshni-b** [AfricasTalkingLtd/africastalking-python#31]
Is there any documentation or sample code for implementing **USSD** using Python? I can only see a PHP example on the website.

**Comment by zlyxero** [comment]
Hi @roshni-b you can find sample code here : [Building an offline account management application using USSD](https://build.at-labs.io/course/5c0a92ee155dd30042e5e578) . I hope this helps :)

**Comment by roshni-b** [comment]
Thank you!
