### ISSUE TITLE
Update base api url to the new endpoint

### ISSUE THREAD

**Issue by felixcheruiyot** [AfricasTalkingLtd/africastalking-python#36]
https://github.com/AfricasTalkingLtd/africastalking-python/blob/f8e54a950777899b4332fc6b99ce4b7a281978aa/africastalking/Service.py#L149

Got an email suggesting we should now use content.africastalking.com.

**Comment by aksalj** [comment]
Was fix with [update content base url](https://github.com/AfricasTalkingLtd/africastalking-python/commit/31fb4b7c3403e4bb559f4c3441e0f73ceb939fbf)
