### ISSUE TITLE
AfricasTalkingGateWay

### ISSUE THREAD

**Issue by GramisJ** [AfricasTalkingLtd/africastalking-python#38]
Hi AfricasTalking
I'm unable to use your api key
I get the following error wherever i try to run my script.Kindly help

Traceback (most recent call last):
  File "routes.py", line 2, in <module>
    from send_message import send_the_message
  File "C:\Users\admn\Desktop\Dream_Team\BulkySMS\send_message.py", line 2, in <module>
    from africas_talking_api import send_the_sms
  File "C:\Users\admn\Desktop\Dream_Team\BulkySMS\africas_talking_api.py", line 1, in <module>
    from AfricasTalkingGateway import AfricasTalkingGateway, AfricasTalkingGatewayException
ModuleNotFoundError: No module named 'AfricasTalkingGateway'

**Comment by AnthonyLimo** [comment]
Hi @GramisJ 

Kindly use the SDK provided. A typical script for the bulk SMS API looks something like this:

1. Start by adding the `africastalking` package using `pip3 install africastalking`

2. Import the SDK into your app and use it:

```
import africastalking

africastalking.initialize(username="USERNAME", api_key="KEY")
sms = africastalking.SMS
resp = sms.send("Hello, world", "+254727545805")
print(resp)
```

**Comment by AnthonyLimo** [comment]
You can also take a look at these examples: https://github.com/AfricasTalkingLtd/africastalking-python/tree/master/example

**Comment by GramisJ** [comment]
Thank you. A colleague of yours had sorted me out.

**Comment by AnthonyLimo** [comment]
No worries. Glad you got sorted out.
