### ISSUE TITLE
It sure would be nice to be able to send dynamic messages. 

### ISSUE THREAD

**Issue by GrishonNganga** [AfricasTalkingLtd/africastalking-python#39]
Can one send messages to a list of people, but the message being sent be dynamic?

From what I understand, the only way I would be able to do so is by making multiple requests. That is not a good use case for me as I need the response immediately for the tasks being done otherwise I would push the work to a worker.

An example of how it would look is something as follows. 

sms.send("Hello {first_name} {lastname}!", [{"first_name": "Grishon", "last_name": "Gikima"}, {"first_name":"Kelvin", "last_name": "Ng'ang'a"}], ["+2547xxxxxx", "+2547xxxxxx"])

**Comment by The-macharia** [comment]
I don't think this needs to be a feature. The idea is to send an SMS to one or multiple recipients.
This idea brings the headache of validating an arbitrary number of parameters while still ensuring no malicious params pass.
