### ISSUE TITLE
Why am I getting the error 'Supplied Authentication is Invalid'?

### ISSUE THREAD

**Issue by wathika-eng** [AfricasTalkingLtd/africastalking-python#52]
Despite reading this [help](https://help.africastalking.com/en/articles/1036048-why-am-i-getting-the-error-supplied-authentication-is-invalid) and having the correct API key and username, I still get the below error.

`Encountered an error while sending SMS: The supplied authentication is invalid
`

**Comment by ZenHank** [comment]
How did you solve this problem? I'm in the same situation.
