### ISSUE TITLE
Python3 AfricasTalkingGateway.py Changes

### ISSUE THREAD

**Issue by mkn2016** [AfricasTalkingLtd/africastalking-python#6]
**AfricastalkingGateway.py Fixes**

- line 227 of AfricasTalkingGateway.py - changed print(response) instead of print response.

- import urllib2 is depracted in python3. The urllib2 and urllib in python2.x were combined and split across various modules in python3. Instead of:
`import` urllib2
import urllib
`

For python3:
`from urllib.request import Request, urlopen
from urllib.parse import urlencode
`

You can try wrapping it in a try-except block to check for both. e.g
`try:
        from urllib.request import urlopen
except:
        from urllib2 import urlopen
`
After doing this, it works. Danke!

**Comment by ianjuma** [comment]
submit a PR maybe?

**Comment by ianjuma** [comment]
Hi @mkn2016 the library has moved to requests; it's updated on PyPI as 1.7

Please update.
