### ISSUE TITLE
Update the file on the website

### ISSUE THREAD

**Issue by giantas** [AfricasTalkingLtd/africastalking-python#9]
The Gateway file on the official website is an older version and would give problems to a new user if that was the first place they checked (since it does not support py3).

**Comment by v1kku** [comment]
The docs should just link to this repo and not a downloadable python file.

**Comment by giantas** [comment]
This is the [link](http://docs.africastalking.com/smslibraries/python)

**Comment by ianjuma** [comment]
Hi @giantas @v1kku we're working on having one true source that can be versioned and tracked. We will update this.
